# Generated by Django 2.2 on 2019-05-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0004_customer_utax'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCusterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
                ('customer', models.ForeignKey(on_delete=True, to='index.customer')),
                ('user', models.ForeignKey(on_delete=True, to='index.user')),
            ],
            options={
                'verbose_name': '总表',
                'verbose_name_plural': '总表',
            },
        ),
    ]
