# Generated by Django 2.2 on 2019-06-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tomorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(max_length=11, verbose_name='日期')),
                ('arrange', models.CharField(max_length=20, verbose_name='具体金额')),
                ('customerUnit', models.CharField(max_length=20, verbose_name='单位')),
                ('customerPwd', models.CharField(max_length=200, verbose_name='税号')),
                ('sourceName', models.CharField(max_length=10, verbose_name='开票员')),
                ('customerName', models.CharField(max_length=10, verbose_name='顾客姓名')),
                ('explain', models.CharField(max_length=500, verbose_name='要求')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '明日安排',
                'verbose_name_plural': '明日安排',
            },
        ),
    ]
