# Generated by Django 2.2 on 2019-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomorrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomorrow',
            name='isChange',
            field=models.BooleanField(default=True, verbose_name='是否改变'),
        ),
    ]
