# Generated by Django 2.2 on 2019-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20190608_1741'),
        ('tomorrow', '0002_tomorrow_ischange'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomorrow',
            name='order',
            field=models.ForeignKey(default='', on_delete=True, to='order.order'),
        ),
    ]
