# Generated by Django 2.2 on 2019-04-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.IntegerField(max_length=50, verbose_name='手机号')),
                ('uwei', models.CharField(max_length=20, verbose_name='微信')),
                ('uqq', models.IntegerField(max_length=15, verbose_name='QQ')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('uaddres', models.CharField(max_length=50, verbose_name='收货地址')),
                ('uchoice', models.CharField(default='纸质发票', max_length=10, verbose_name='发票类型')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='单位名称')),
                ('upwd', models.CharField(max_length=50, verbose_name='单位税号')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '单位信息',
                'verbose_name_plural': '单位信息',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=11, verbose_name='账号')),
                ('upwd', models.CharField(max_length=20, verbose_name='密码')),
                ('uemail', models.EmailField(default=None, max_length=30, verbose_name='邮箱')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
                ('customer', models.ManyToManyField(to='index.customer')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(max_length=100, verbose_name='数量')),
                ('isActive', models.BooleanField(choices=[(0, '未安排'), (1, '已安排'), (2, '待寄出'), (3, '待付款'), (4, '已完结')], default=0, verbose_name='状态')),
                ('startTime', models.DateTimeField(auto_now_add=True, verbose_name='接单时间')),
                ('endTime', models.DateTimeField(verbose_name='预期完结时间')),
                ('customer', models.ForeignKey(on_delete=True, to='index.customer')),
                ('unit', models.ForeignKey(on_delete=True, to='index.unit')),
                ('user', models.ForeignKey(on_delete=True, to='index.user')),
            ],
            options={
                'verbose_name': '订单总表',
                'verbose_name_plural': '订单总表',
            },
        ),
        migrations.CreateModel(
            name='allData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
                ('unit', models.ForeignKey(on_delete=True, to='index.unit')),
                ('user', models.ForeignKey(on_delete=True, to='index.user')),
            ],
            options={
                'verbose_name': '总表',
                'verbose_name_plural': '总表',
                'ordering': ['unit'],
            },
        ),
    ]
