# Generated by Django 2.2 on 2019-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190430_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='unit',
            field=models.ManyToManyField(to='index.unit'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uphone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
