# Generated by Django 2.2 on 2019-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190430_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uTax',
            field=models.CharField(default='4', max_length=10, verbose_name='发票点子'),
        ),
    ]
