# Generated by Django 2.2 on 2019-05-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190501_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
