# Generated by Django 2.2 on 2019-05-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='uTax',
        ),
    ]
