# Generated by Django 2.2 on 2019-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_customer_utax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='uname',
            field=models.CharField(max_length=20, verbose_name='客户来源'),
        ),
    ]
