# Generated by Django 2.2 on 2019-05-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190510_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='unit',
        ),
    ]
