# Generated by Django 2.2 on 2019-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0005_auto_20190501_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机号')),
                ('uwei', models.CharField(max_length=20, verbose_name='微信')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('uaddres', models.CharField(max_length=200, verbose_name='加油站地址')),
                ('uchoice', models.CharField(default='纸质发票', max_length=10, verbose_name='发票类型')),
                ('uTax', models.CharField(default='3', max_length=10, verbose_name='发票点子')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '加油员信息',
                'verbose_name_plural': '加油员信息',
            },
        ),
        migrations.CreateModel(
            name='userSourceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
                ('source', models.ForeignKey(on_delete=True, to='source.source')),
                ('user', models.ForeignKey(on_delete=True, to='index.user')),
            ],
            options={
                'verbose_name': '加油员总表',
                'verbose_name_plural': '加油员总表',
            },
        ),
    ]
