# Generated by Django 2.2 on 2019-05-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
        ('index', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=100, verbose_name='数量')),
                ('isActive', models.BooleanField(choices=[(0, '未安排'), (1, '已安排'), (2, '待寄出'), (3, '待付款'), (4, '已完结')], default=0, verbose_name='状态')),
                ('startTime', models.DateTimeField(auto_now_add=True, verbose_name='接单时间')),
                ('endTime', models.DateTimeField(verbose_name='预期完结时间')),
                ('customer', models.ForeignKey(on_delete=True, to='index.customer')),
                ('source', models.ForeignKey(on_delete=True, to='source.source')),
                ('unit', models.ForeignKey(on_delete=True, to='index.unit')),
                ('user', models.ForeignKey(on_delete=True, to='index.user')),
            ],
            options={
                'verbose_name': '订单总表',
                'verbose_name_plural': '订单总表',
            },
        ),
    ]
