# Generated by Django 2.2 on 2019-05-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='explain',
            field=models.CharField(default='', max_length=300, verbose_name='备注'),
        ),
    ]
