# Generated by Django 2.2 on 2019-05-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[(0, '未安排'), (1, '已安排'), (2, '待寄出'), (3, '待付款'), (4, '已完结')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
