# Generated by Django 2.2 on 2019-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190502_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='endTime',
            field=models.CharField(max_length=50, verbose_name='预期完结时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='startTime',
            field=models.CharField(max_length=50, verbose_name='接单时间'),
        ),
    ]
