# Generated by Django 2.2 on 2019-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190502_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(max_length=20, verbose_name='状态'),
        ),
    ]
