# Generated by Django 2.2 on 2019-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190502_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='style',
            field=models.CharField(default='纸质发票', max_length=10, verbose_name='发票类型'),
        ),
    ]
