# Generated by Django 2.2 on 2019-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190505_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notComple',
            field=models.IntegerField(default=0, max_length=20, verbose_name='未打完'),
        ),
    ]
