# Generated by Django 2.2 on 2019-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_notcomple'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Delivery',
            field=models.CharField(default='韵达快递', max_length=10, verbose_name='发货方式'),
        ),
    ]
