# Generated by Django 2.2 on 2019-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actualCost',
            field=models.IntegerField(default=0, verbose_name='实际成本'),
        ),
        migrations.AlterField(
            model_name='order',
            name='actualProfit',
            field=models.IntegerField(default=0, verbose_name='实际利润'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimatProfit',
            field=models.IntegerField(default=0, verbose_name='预计利润'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimateCost',
            field=models.IntegerField(default=0, verbose_name='预计成本'),
        ),
        migrations.AlterField(
            model_name='order',
            name='netReceiots',
            field=models.IntegerField(default=0, verbose_name='实收'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recivable',
            field=models.IntegerField(default=0, verbose_name='应收'),
        ),
    ]
