# Generated by Django 2.2 on 2019-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190506_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notComple',
            field=models.IntegerField(default=0, verbose_name='未打完'),
        ),
    ]
