# Generated by Django 2.2 on 2019-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_customer_unit'),
        ('order', '0016_order_sourcename'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saveNumber', models.CharField(max_length=500, verbose_name='安排')),
                ('order', models.ForeignKey(on_delete=True, to='order.order')),
                ('user', models.ForeignKey(on_delete=True, to='index.user')),
            ],
        ),
    ]
