# Generated by Django 2.2 on 2019-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20190521_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdate',
            name='saveNumber',
            field=models.CharField(max_length=15000, verbose_name='安排'),
        ),
    ]
