# Generated by Django 2.2 on 2019-05-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20190521_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notComple',
            field=models.CharField(default=0, max_length=20, verbose_name='完成情况'),
        ),
    ]
