# Generated by Django 2.2 on 2019-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20190531_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notComple',
            field=models.CharField(max_length=20, verbose_name='完成情况'),
        ),
    ]
