# Generated by Django 2.2 on 2019-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_customer_unit'),
        ('order', '0021_auto_20190531_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=500, verbose_name='图片路径')),
                ('order', models.ForeignKey(on_delete=True, to='order.order')),
                ('user', models.ForeignKey(on_delete=True, to='index.user')),
            ],
        ),
    ]
