# Generated by Django 2.2 on 2019-06-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
