# Generated by Django 2.2 on 2019-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_img_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Delivery',
            field=models.CharField(default='韵达快递', max_length=30, verbose_name='发货方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='actualCost',
            field=models.CharField(default=0, max_length=30, verbose_name='实际成本'),
        ),
        migrations.AlterField(
            model_name='order',
            name='actualProfit',
            field=models.CharField(default=0, max_length=30, verbose_name='实际利润'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimatProfit',
            field=models.CharField(default=0, max_length=30, verbose_name='预计利润'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimateCost',
            field=models.CharField(default=0, max_length=30, verbose_name='预计成本'),
        ),
        migrations.AlterField(
            model_name='order',
            name='netReceiots',
            field=models.CharField(default=0, max_length=30, verbose_name='实收'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recivable',
            field=models.CharField(default=0, max_length=30, verbose_name='应收'),
        ),
    ]
